"46087": Neah Bay
"46088": New Dungeness
"46206": La Perouse Bank
"46029": Columbia River Bar
"46243": Clatsop Spit
"46248": Astoria Canyon
"46097": Newport Shelf
"46214": Point Reyes
"46026": San Francisco
"46237": San Francisco Bar
